// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API.Data;

#nullable disable

namespace Web_API.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20250211081340_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_API.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Rockstar Games",
                            Platform = "Current Gen Consoles and PC",
                            Publisher = "Take Two Interactive",
                            Title = "Red Dead Redemption II"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Ubisoft",
                            Platform = "PC and old consoles",
                            Publisher = "Ubisoft",
                            Title = "Farcry 2"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Quantam Dream",
                            Platform = "PC and Playstation",
                            Publisher = "Sony Interactive Games",
                            Title = "Detroit Become Human"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "2K Games",
                            Platform = "PC and old consoles",
                            Publisher = "Take Two Interactive",
                            Title = "Mafia II"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
